name: apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tofu
    if: github.ref == 'refs/heads/main'
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: setup
        id: setup
        uses: opentofu/setup-opentofu@v1
      
      - name: init
        id: init
        run: tofu init

      - name: fmt
        id: fmt
        continue-on-error: true
        run: tofu fmt -check

      - name: validate
        id: validate
        run: tofu validate

      - name: plan
        id: plan
        if: steps.validate.outcome == 'success'
        run: tofu plan

      - name: apply
        id: apply
        if: steps.plan.outcome == 'success'
        run: tofu apply -auto-approve